
	IF NOT EXISTS(
		SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW') 
		AND IDUser = 1 
		AND Name = 'DECIMALSEPARATOR')
	BEGIN
		INSERT INTO TBLPrefs (IDUser, IDScreen, Name, Preference)
		VALUES (1, (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW'), 'DECIMALSEPARATOR', 'DOT')
	END