IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW'
AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View'))
AND [NAME] = 'PAGINATIONREPORTQTY'
AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
INSERT INTO TBLPrefs (
IDUser,
IDScreen,
[Name],
[Preference]
)
VALUES (
(SELECT IDUser FROM TBLUser WHERE Code = 'ADMIN'),
(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')),
'PAGINATIONREPORTQTY',
'100'
)
END
GO



IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW'
AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View'))
AND [NAME] = 'FORMATTIME'
AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
INSERT INTO TBLPrefs (
IDUser,
IDScreen,
[Name],
[Preference]
)
VALUES (
(SELECT IDUser FROM TBLUser WHERE Code = 'ADMIN'),
(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')),
'FORMATTIME',
'1'
)
END
GO



IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW'
AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View'))
AND [NAME] = 'PAGINATIONREPORT'
AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
VALUES ('PAGINATIONREPORT', 100,
(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW'
AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')),
(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO

--TELA MAINVIEW - Código de tela principal do médulo de gestão
IF NOT EXISTS (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View'))
BEGIN
	INSERT INTO TBLScreen (Code,Name,NameEN,FlgProduct,IDAplication,DtCreation, ContextPrint)
	VALUES ('MAINVIEW', 'MAINVIEW - Tela principal do Módulo de Gestão', 'MAINVIEW - Main Screen of Manager Module', 1, (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View'), GETDATE(), 0)
END
GO

--INSERTS COM OS VALORES DEFAULT DAS PREFERÊNCIAS DO USUÁRIO ADMIN 
--DECIMAL DIGITS FOR UNIT1 
IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')) 
	AND [NAME] = 'DECIMALDIGITSUNIT1' 
	AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
	INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
	VALUES ('DECIMALDIGITSUNIT1', 2, 
	(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')), 
	(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO

--DECIMAL DIGITS FOR UNIT2
IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')) 
	AND [NAME] = 'DECIMALDIGITSUNIT2' 
	AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
	INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
	VALUES ('DECIMALDIGITSUNIT2', 2, 
	(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')), 
	(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO 

--DECIMAL DIGITS FOR UNIT3
IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')) 
	AND [NAME] = 'DECIMALDIGITSUNIT3' 
	AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
	INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
	VALUES ('DECIMALDIGITSUNIT3', 2, 
	(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')), 
	(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO

--DECIMAL DIGITS FOR INDICATORS
IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')) 
	AND [NAME] = 'DECIMALDIGITSINDICATORS' 
	AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
	INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
	VALUES ('DECIMALDIGITSINDICATORS', 2, 
	(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')), 
	(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO

--DECIMAL DIGITS FOR PERCENTUAL
IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')) 
	AND [NAME] = 'DECIMALDIGITSPERCENTUAL' 
	AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
	INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
	VALUES ('DECIMALDIGITSPERCENTUAL', 2, 
	(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')), 
	(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO

--DECIMAL DIGITS FOR SPEED UN/S
IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')) 
	AND [NAME] = 'DECIMALDIGITSSPEEDUNS' 
	AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
	INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
	VALUES ('DECIMALDIGITSSPEEDUNS', 4, 
	(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')), 
	(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO

--DECIMAL DIGITS FOR SPEED UN/MIN
IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')) 
	AND [NAME] = 'DECIMALDIGITSSPEEDUNMIN' 
	AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
	INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
	VALUES ('DECIMALDIGITSSPEEDUNMIN', 4, 
	(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')), 
	(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO

--DECIMAL DIGITS FOR SPEED UN/H
IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')) 
	AND [NAME] = 'DECIMALDIGITSSPEEDUNH' 
	AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
	INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
	VALUES ('DECIMALDIGITSSPEEDUNH', 4, 
	(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')), 
	(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO

--DECIMAL DIGITS FOR STDTIME S/UN
IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')) 
	AND [NAME] = 'DECIMALDIGITSSTDTIMESUN' 
	AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
	INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
	VALUES ('DECIMALDIGITSSTDTIMESUN', 4, 
	(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')), 
	(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO

--DECIMAL DIGITS FOR STDTIME MIN/UN
IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')) 
	AND [NAME] = 'DECIMALDIGITSSTDTIMEMINUN' 
	AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
	INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
	VALUES ('DECIMALDIGITSSTDTIMEMINUN', 4, 
	(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')), 
	(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO

--DECIMAL DIGITS FOR STDTIME H/UN
IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')) 
	AND [NAME] = 'DECIMALDIGITSSTDTIMEHUN' 
	AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
	INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
	VALUES ('DECIMALDIGITSSTDTIMEHUN', 4, 
	(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')), 
	(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO

--DECIMAL DIGITS FOR CREW
IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')) 
	AND [NAME] = 'DECIMALDIGITSCREW' 
	AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
	INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
	VALUES ('DECIMALDIGITSCREW', 4, 
	(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')), 
	(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO

--REPORT TIMEOUT
IF NOT EXISTS (SELECT IDPref FROM TBLPrefs WHERE IDScreen = (SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')) 
	AND [NAME] = 'REPORTTIMEOUT' 
	AND IDUser = (SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
BEGIN
	INSERT INTO TBLPrefs ([NAME], Preference, IDScreen, IDUser)
	VALUES ('REPORTTIMEOUT', 30, 
	(SELECT IDScreen FROM TBLScreen WHERE Code = 'MAINVIEW' 
	AND IDAplication = (SELECT IDAplication FROM TBLAplication WHERE Code = 'PCF4View')), 
	(SELECT IDUser FROM TBLUSER WHERE Code = 'ADMIN'))
END
GO						